### PR TITLE
New features

### PR DESCRIPTION
**Pull request by towerofnix**

### CODE REVIEW

**Comment by towerofnix** [comment]
Don't merge right now, not quite finished :P

**Comment by towerofnix** [comment]
Fixed a bit.

**Comment by BookOwl** [comment]
So this saves the size of the window when closed?

**Comment by towerofnix** [comment]
Yup!

**Comment by BookOwl** [comment]
Is it ready to merge?

**Comment by towerofnix** [comment]
I think so, yeah.

**Pull request merged**
